version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
  pre_build:
    commands:
      - echo "Web unit / typecheck"
  build:
    commands:
      - cd web
      - npm ci
      - npm run typecheck
      - npm run test
      - npm run scan:secrets
artifacts:
  files:
    - '**/*'
  name: web-unit-test
